name: Deploy to Heroku

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests (if any)
      run: npm test --if-present
    
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.14
      if: github.ref == 'refs/heads/main'
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        appdir: "."
        healthcheck: "https://${{ secrets.HEROKU_APP_NAME }}.herokuapp.com/health"
        checkstring: "ok"
        delay: "10"
        procfile: "Procfile"
        rollbackonhealthcheckfailed: true
